openapi: "3.0.0"
info:
  version: 1.5
  title: Stomp Test
  license:
    name: The Apache Software License, Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
servers:
- url: http://localhost:8080/stomp-test-v1.5
  name: local