---
openapi: 3.1.0
components:
  schemas:
    Action:
      description: Executable action
      type: string
      enum:
      - SUBSCRIBE
      - UNSUBSCRIBE
    Command:
      description: Action to execute for a share
      type: object
      xml:
        name: command
      required:
      - action
      - key
      properties:
        action:
          $ref: "#/components/schemas/Action"
        key:
          type: string
          description: the share
    error:
      description: Structured error message
      type: object
      xml:
        name: error
      properties:
        message:
          type: string
          description: The error message
          xml:
            attribute: true
        path:
          type: string
          description: "On validation errors: the property which was invalid"
          xml:
            attribute: true
        invalidValue:
          type: string
          description: "On validation errors: the value which was invalid"
          xml:
            attribute: true
    errors:
      description: Error response
      type: object
      xml:
        name: errors
      properties:
        error:
          type: array
          items:
            $ref: "#/components/schemas/error"
        requestUri:
          type: string
          description: Request URI
          xml:
            attribute: true
        type:
          type: string
          description: Error type
          xml:
            attribute: true
    index:
      description: Index page with HATEOS links
      type: object
      xml:
        name: index
      properties:
        links:
          type: array
          items: {}
          xml:
            name: link
    link:
      description: HTTP Link
      type: object
      properties:
        href:
          type: string
          description: the link target as a URI-Reference
          examples:
          - https://microsoft.com
        rel:
          type: string
          description: The relation type of a link
          examples:
          - self
        title:
          type: string
          description: used to label the destination of a link such that it can be
            used as a human-readable identifier
        type:
          type: string
          description: a hint indicating what the media type of the result of dereferencing
            the link should be
          examples:
          - text/html
        method:
          type: string
          description: HTTP method
          examples:
          - get
    quote:
      description: A quote is the current price for a share
      readOnly: true
      type: object
      xml:
        name: quote
      required:
      - share
      properties:
        share:
          description: the share
          type: object
          $ref: "#/components/schemas/share"
        price:
          type: number
          format: float
          description: the price
          examples:
          - 12.34
          xml:
            attribute: true
        currency:
          type: string
          description: currency code
          default: EUR
          xml:
            attribute: true
        from:
          type: string
          format: date
          examples:
          - 2022-03-10
          description: "date of origin, as defined in `ISO8601`"
          externalDocs:
            url: https://en.wikipedia.org/wiki/ISO_8601
          xml:
            attribute: true
        links:
          readOnly: true
          type: array
          items:
            description: HTTP Link
            type: object
            properties:
              href:
                type: string
                description: the link target as a URI-Reference
                examples:
                - https://microsoft.com
              rel:
                type: string
                description: The relation type of a link
                examples:
                - self
              title:
                type: string
                description: used to label the destination of a link such that it
                  can be used as a human-readable identifier
              type:
                type: string
                description: a hint indicating what the media type of the result of
                  dereferencing the link should be
                examples:
                - text/html
              method:
                type: string
                description: HTTP method
                examples:
                - get
          xml:
            name: link
    quotes:
      readOnly: true
      type: object
      xml:
        name: quotes
      properties:
        quotes:
          type: array
          items:
            $ref: "#/components/schemas/quote"
          xml:
            name: quote
    share:
      type: object
      description: "Shares are identified by stock symbols, and may have an name for\
        \ readability."
      xml:
        name: share
      required:
      - key
      properties:
        key:
          type: string
          description: Stock symbol
          examples:
          - MSFT
          pattern: "[A-Z0-9.]*"
          minLength: 1
          maxLength: 25
          xml:
            attribute: true
        name:
          type: string
          description: Human readable name
          examples:
          - Microsoft Corp.
          minLength: 1
          maxLength: 80
          xml:
            attribute: true
        links:
          readOnly: true
          type: array
          items:
            description: HTTP Link
            type: object
            properties:
              href:
                type: string
                description: the link target as a URI-Reference
                examples:
                - https://microsoft.com
              rel:
                type: string
                description: The relation type of a link
                examples:
                - self
              title:
                type: string
                description: used to label the destination of a link such that it
                  can be used as a human-readable identifier
              type:
                type: string
                description: a hint indicating what the media type of the result of
                  dereferencing the link should be
                examples:
                - text/html
              method:
                type: string
                description: HTTP method
                examples:
                - get
          xml:
            name: link
    shares:
      readOnly: true
      type: object
      xml:
        name: shares
      properties:
        shares:
          type: array
          items:
            $ref: "#/components/schemas/share"
          xml:
            name: share
tags:
- name: Quotes
  description: receive quotes for shares
- name: Shares
  description: subscribe to shares on the stock market
paths:
  /rest:
    get:
      description: Link to available resources
      responses:
        "200":
          description: The root resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/index"
            application/xml:
              schema:
                $ref: "#/components/schemas/index"
  /rest/quotes:
    get:
      description: get quotes
      tags:
      - Quotes
      parameters:
      - in: header
        name: X-Caller-ID
        schema:
          type: string
      - in: header
        name: X-Request-ID
        schema:
          type: string
      - description: Stock symbols
        example:
        - GOOG
        name: key
        in: query
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Quotes received
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/quotes"
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/quote"
        "404":
          description: No subscription found
  /rest/quotes/{key}:
    get:
      description: get a quote
      tags:
      - Quotes
      parameters:
      - in: header
        name: X-Caller-ID
        schema:
          type: string
      - in: header
        name: X-Request-ID
        schema:
          type: string
      - description: "Stock symbol, see [quote.cnbc.com](https://quote.cnbc.com)"
        example: BMW.DE
        name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Quote received
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/quote"
            application/xml:
              schema:
                $ref: "#/components/schemas/quote"
        "404":
          description: Subscription not found
  /rest/shares:
    get:
      description: List all subscriptions
      tags:
      - Shares
      parameters:
      - in: header
        name: X-Caller-ID
        schema:
          type: string
      - in: header
        name: X-Request-ID
        schema:
          type: string
      responses:
        "200":
          description: All subscriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/share"
            application/xml:
              schema:
                $ref: "#/components/schemas/shares"
    post:
      description: Add a share to your list of subscriptions
      operationId: addShare
      tags:
      - Shares
      parameters:
      - in: header
        name: X-Caller-ID
        schema:
          type: string
      - in: header
        name: X-Request-ID
        schema:
          type: string
      - description: provide a Correlation-Id header to receive a response for your
          operation when it finished.
        name: Correlation-Id
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/share"
          application/xml:
            schema:
              $ref: "#/components/schemas/share"
        required: true
      responses:
        "201":
          description: Share queued for subscription
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/share"
            application/xml:
              schema:
                $ref: "#/components/schemas/share"
        "500":
          description: Queuing failed
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
            application/xml:
              schema:
                $ref: "#/components/schemas/errors"
  /rest/shares/{key}:
    delete:
      description: Remove a subscription of a share
      tags:
      - Shares
      parameters:
      - in: header
        name: X-Caller-ID
        schema:
          type: string
      - in: header
        name: X-Request-ID
        schema:
          type: string
      - description: Stock symbol
        example: GOOG
        name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Subscription removed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/share"
            application/xml:
              schema:
                $ref: "#/components/schemas/share"
        "404":
          description: Subscription was not found
    get:
      description: Find a share subscription
      tags:
      - Shares
      parameters:
      - in: header
        name: X-Caller-ID
        schema:
          type: string
      - in: header
        name: X-Request-ID
        schema:
          type: string
      - description: "Stock symbol, see [quote.cnbc.com](https://quote.cnbc.com)"
        example: BMW.DE
        name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Subscription found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/share"
            application/xml:
              schema:
                $ref: "#/components/schemas/share"
        "404":
          description: Subscription not found
  /rest/{path}:
    options:
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
info:
  title: Stomp Test
  version: "1.8"
  description: A sample application for websockets and stomp on Wildfly
  contact:
    email: mail@johannes-beck.name
  license:
    name: "The Apache Software License, Version 2.0"
    url: https://www.apache.org/licenses/LICENSE-2.0.txt
