apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: activemq-artemis
  name: activemq-artemis
  namespace: activemq-artemis
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
