apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-sidecar
  namespace: stomp-test
spec:
  mode: sidecar
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    exporters:
      logging: {}
      otlp:
        endpoint: "jaeger-all-in-one-collector.observability:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
    processors:
      batch: {}
    extensions:
      health_check: {}
      zpages:
        endpoint: :55679
    service:
      extensions:
        - zpages
        - health_check
      telemetry:
        logs:
          level: warn
      pipelines:
        traces:
          exporters:
            - otlp
          processors:
            - batch
          receivers:
            - otlp
        metrics:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - prometheus
