apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresql-persistent
  name: postgresql
  namespace: stomp-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
