apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stomp-test-ingress
  namespace: stomp-test
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 40m
    #nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    cert-manager.io/cluster-issuer: x1-cluster-issuer
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - stomp-test.k8s.x1
    secretName: pki-wildfly-secret
  - hosts:
    - activemq-artemis.k8s.x1
    secretName: pki-activemq-artemis-secret
  rules:
  - host: stomp-test.k8s.x1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wildfly
            port: 
              name: https
  - host: activemq-artemis.k8s.x1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: activemq-artemis
            port:
              name: http
