apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stomp-test-ingress
  namespace: stomp-test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 40m
    #nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
spec:
  tls:
  - hosts:
    - stomp-test.docker.x1
    secretName: pki-wildfly-secret
  - hosts:
    - activemq-artemis.docker.x1
    secretName: pki-activemq-artemis-secret
  rules:
  - host: stomp-test.docker.x1
    http:
      paths:
      - path: /
        backend:
          serviceName: wildfly
          servicePort: https
  - host: activemq-artemis.docker.x1
    http:
      paths:
      - path: /
        backend:
          serviceName: activemq-artemis
          servicePort: http
