version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd
    command: ["etcd", "--listen-client-urls", "http://0.0.0.0:2379", "--advertise-client-urls", "http://etcd:2379"]
    environment:
     - ETCD_ENABLE_V2=true
  db:
    image: registry.x1/j7beck/x1-postgres-stomp-test:1.8
    container_name: stomp-test-db
    volumes:
     - /opt/docker/x1/certs/stomp-test-db.key:/etc/pki/tls/private/node.key:ro
     - /opt/docker/x1/certs/stomp-test-db.crt:/etc/pki/tls/certs/node.crt:ro
  activemq-artemis:
    image: registry.x1/j7beck/x1-activemq-artemis
    container_name: activemq-artemis
    environment:
     - SERVICE_NAME=activemq-artemis
     - ARTEMIS_USER=artemis
     - ARTEMIS_PASSWORD=artemis
    volumes:
     - /opt/docker/x1/certs/activemq-artemis.key:/etc/pki/tls/private/node.key:ro
     - /opt/docker/x1/certs/activemq-artemis.crt:/etc/pki/tls/certs/node.crt:ro
    ports:
     - 8161:8161
  wildfly:
    image: registry.x1/j7beck/x1-wildfly-jar-stomp-test:1.8.0-SNAPSHOT
    environment:
     - X1_SERVICE_REGISTRY_ETCD=http://etcd:2379
     - X1_SERVICE_REGISTRY_STAGE=docker
     - OTEL_COLLECTOR=otel-collector
     - OTEL_SDK_DISABLED=false
     - DB_SERVER=db
     - DB_PORT=5432
     - DB_NAME=stocks
     - ACTIVEMQ_SERVER=activemq-artemis
     - GC_MAX_METASPACE_SIZE=256
     - GC_METASPACE_SIZE=96
     - SERVICE_NAME=stomp-test
    volumes:
     - /opt/docker/x1/certs/docker.key:/etc/pki/tls/private/node.key:ro
     - /opt/docker/x1/certs/docker.crt:/etc/pki/tls/certs/node.crt:ro
    ports:
     - 8080:8080
     - 8443:8443
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
