version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.6
    network_mode: bridge
    domainname: docker.x1
    command: ["-listen-client-urls", "http://0.0.0.0:2379,http://0.0.0.0:4001", "-advertise-client-urls", "http://etcd:2379,http://etcd:4001"]
  db:
    image: registry.x1/j7beck/x1-postgres-stomp-test:1.7
    hostname: stomp-test-db
    domainname: docker.x1
    container_name: stomp-test-db
    network_mode: bridge
    volumes:
     - /opt/docker/x1/certs/stomp-test-db.key:/etc/pki/tls/private/node.key:ro
     - /opt/docker/x1/certs/stomp-test-db.crt:/etc/pki/tls/certs/node.crt:ro
  activemq-artemis:
    image: registry.x1/j7beck/x1-activemq-artemis
    hostname: activemq-artemis
    domainname: docker.x1
    container_name: activemq-artemis
    network_mode: bridge
    environment:
     - SERVICE_NAME=activemq-artemis
    volumes:
     - /opt/docker/x1/certs/activemq-artemis.key:/etc/pki/tls/private/node.key:ro
     - /opt/docker/x1/certs/activemq-artemis.crt:/etc/pki/tls/certs/node.crt:ro
  wildfly:
    image: registry.x1/j7beck/x1-wildfly-jar-stomp-test:1.7.0-SNAPSHOT
    domainname: docker.x1
    network_mode: bridge
    environment:
     - X1_SERVICE_REGISTRY_ETCD=http://etcd:4001
     - X1_SERVICE_REGISTRY_STAGE=docker
     - DB_SERVER=db
     - DB_PORT=5432
     - ACTIVEMQ_SERVER=activemq-artemis
     - GC_MAX_METASPACE_SIZE=256
     - GC_METASPACE_SIZE=96
     - SERVICE_NAME=stomp-test
    volumes:
     - /opt/docker/x1/certs/docker.key:/etc/pki/tls/private/node.key:ro
     - /opt/docker/x1/certs/docker.crt:/etc/pki/tls/certs/node.crt:ro
    links:
      - activemq-artemis:activemq-artemis
      - db:db
      - etcd:etcd
