CREATE SCHEMA stocks;

CREATE SEQUENCE stocks.hibernate_sequence;

CREATE TABLE stocks.share (
  id bigint NOT NULL,
  key character varying(25) NOT NULL,
  name character varying(80) NOT NULL,
  version bigint,
  CONSTRAINT share_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_key ON stocks.share (key);
CREATE INDEX idx_name ON stocks.share (name);

CREATE TABLE stocks.jboss_ejb_timer (
  ID VARCHAR PRIMARY KEY NOT NULL,
  TIMED_OBJECT_ID VARCHAR NOT NULL,
  INITIAL_DATE TIMESTAMP,
  REPEAT_INTERVAL BIGINT,
  NEXT_DATE TIMESTAMP,
  PREVIOUS_RUN TIMESTAMP,
  PRIMARY_KEY VARCHAR,
  INFO TEXT,
  TIMER_STATE VARCHAR,
  SCHEDULE_EXPR_SECOND VARCHAR,
  SCHEDULE_EXPR_MINUTE VARCHAR,
  SCHEDULE_EXPR_HOUR VARCHAR,
  SCHEDULE_EXPR_DAY_OF_WEEK VARCHAR,
  SCHEDULE_EXPR_DAY_OF_MONTH VARCHAR,
  SCHEDULE_EXPR_MONTH VARCHAR,
  SCHEDULE_EXPR_YEAR VARCHAR,
  SCHEDULE_EXPR_START_DATE VARCHAR,
  SCHEDULE_EXPR_END_DATE VARCHAR,
  SCHEDULE_EXPR_TIMEZONE VARCHAR,
  AUTO_TIMER BOOLEAN,
  TIMEOUT_METHOD_DECLARING_CLASS VARCHAR,
  TIMEOUT_METHOD_NAME VARCHAR,
  TIMEOUT_METHOD_DESCRIPTOR VARCHAR,
  CALENDAR_TIMER BOOLEAN,
  PARTITION_NAME VARCHAR NOT NULL,
  NODE_NAME VARCHAR);

CREATE INDEX JBOSS_EJB_TIMER_IDENX ON stocks.jboss_ejb_timer (PARTITION_NAME, TIMED_OBJECT_ID);
