name: Java IT

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
      - name: Build with Maven
        run: mvn -Pgithub,default -B --no-transfer-progress clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare IT
        run: mvn -Pgithub,wildfly-jar -B --no-transfer-progress -DskipTests install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run TestContainers
        run: mvn -Pgithub,testcontainers -B --no-transfer-progress verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          junit_files: target/**/TEST-*.xml
